mutation RegisterUser(
  $uid: ID!
  $name: String
  $phoneNumber: String!
  $age: Int
  $weight: Float
) {
  updateUser(
    uid: $uid
    name: $name
    phoneNumber: $phoneNumber
    age: $age
    weight: $weight
  ) {
    ...UserUnit
  }
}
