type Query {
  users: [User]
}

type Mutation {
  updateUser(uid: ID!, name: String, age: Int, weight: Float): User
}

type User {
  uid: ID!
  phoneNumber: String!
  name: String
  age: Int
  weight: Float
}

schema {
  query: Query
  mutation: Mutation
}
