type Query {
  users: [User]
  getUser(uid: ID!): User
}

type Mutation {
  updateUser(
    uid: ID!
    name: String
    age: Int
    weight: Float
    userCode: String
  ): User
}

type User {
  uid: ID!
  phoneNumber: String!
  name: String
  age: Int
  weight: Float
  userCode: String
  icon: String
}

schema {
  query: Query
  mutation: Mutation
}
